### PR TITLE
V1.1.0

### PR DESCRIPTION
**Pull request by rebeccahaines1**
update multiqc version to v1.13 and correct regex issue in sompy plugin

- - -
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/multiqc_plugins/10)

### CODE REVIEW

**Review by RachelDuffin — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/multiqc_plugins/10)* status: all files reviewed, 1 unresolved discussion (waiting on @rebeccahaines1)

___
*[`seglh_plugin/modules/sompy/sompy.py` line 233 at r1](https://reviewable.io/reviews/moka-guys/multiqc_plugins/10#-NHiTtuP6n_GcBEc9RHj:-NHiTtuQ7Pzk3XwNFl0I:b-qeyzig) ([raw file](https://github.com/moka-guys/multiqc_plugins/blob/f6c88bdff8fbc611a5cd787a3e4c103ace3c920c/seglh_plugin/modules/sompy/sompy.py#L233)):*
> ```Python
>                 # from the sompy stats.csv file select the sompycmd column
>                 # which contains the input vcf filename after "-o"
>                 m = re.search(r'.*-o\s*(\S+)', data['sompycmd'])
> ```

Is there a better variable name than 'm' - this reduces the need to rely on extensive commenting

**Review by rebeccahaines1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/multiqc_plugins/10)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @RachelDuffin)

___
*[`seglh_plugin/modules/sompy/sompy.py` line 233 at r1](https://reviewable.io/reviews/moka-guys/multiqc_plugins/10#-NHiTtuP6n_GcBEc9RHj:-NHi_LJMA99zg60yupBC:b-896fix) ([raw file](https://github.com/moka-guys/multiqc_plugins/blob/f6c88bdff8fbc611a5cd787a3e4c103ace3c920c/seglh_plugin/modules/sompy/sompy.py#L233)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Is there a better variable name than 'm' - this reduces the need to rely on extensive commenting
</blockquote></details>

Done.

**Review by RachelDuffin — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/multiqc_plugins/10)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @rebeccahaines1)

**Review by RachelDuffin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/multiqc_plugins/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rebeccahaines1)

**Pull request merged**
